# Generated by Django 3.0.8 on 2020-07-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifsc', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=200)),
            ],
        ),
    ]
